### ISSUE TITLE
RuntimeError: Failed to export merged mods

### ISSUE THREAD

**Issue by GreenFire010** [sks316/bcml-steamdeck#5]
When installing, merging or uninstalling following Error pops up: 
Traceback (most recent call last):
  File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/install.py", line 265, in do_and_refresh
    refresh_master_export()
  File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/util.py", line 464, in timed_function
    res = func(*args, **kwargs)
  File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/install.py", line 274, in refresh_master_export
    link_master_mod()
  File "/home/deck/miniconda3/lib/python3.8/site-packages/bcml/install.py", line 745, in link_master_mod
    rsext.manager.link_master_mod(str(output) if output else None)
RuntimeError: Failed to export merged mods

Caused by:
    0: Failed to symlink output folder
    1: No such file or directory (os error 2)

Using Miniconda3-py37_23.1.0-1-Linux-x86_64 (also tried using 3.8 phyton: same result)
from conda.io
and Cemu 1.27.1 installed via emudeck

Followed every step from CryoBytes33 Tutorial identically,but still no success. (https://youtu.be/WfAye3E-0nE)

Also checked the main bcml GitHub issues page and couldn't find anything remotely close to my Error.

Any ideas where to look or what to do?

**Comment by sks316** [comment]
I'm unable to reproduce this, and as this is a BCML issue (not an installer issue) I won't be able to help. Try to open a new issue at [NiceneNerd/BCML](https://github.com/NiceneNerd/BCML).
